### ISSUE TITLE
你好，请问为什么换个图片并不能得到很好的效果？这会与什么因素有关呢？

### ISSUE THREAD

**Issue by uvwatshu** [maple367/pecpy#2]
看到您的ip在深圳，又发过b站播放器的项目，就直接用中文问了hhhhhh
![25086ca4eac4523860e2544372db5d4](https://github.com/user-attachments/assets/57f698c2-b2b9-4744-bd25-1fe01ccee796)

**Comment by maple367** [comment]
看到你已经标记为completed了，这个一般需要调整alpha beta gamma参数来匹配你的工艺参数，我的example里应该只是随便选了两个

**Comment by uvwatshu** [comment]
谢谢你的回复，后面确实也排查到这个问题了，调整好工艺参数之后确实好了不少~

**Comment by maple367** [comment]
> 谢谢你的回复，后面确实也排查到这个问题了，调整好工艺参数之后确实好了不少~

光刻相关加工可以多交流=v=

**Comment by maple367** [comment]
> 谢谢你的回复，后面确实也排查到这个问题了，调整好工艺参数之后确实好了不少~

For more information, please refer to [proximity_main](https://ebeam.mff.uw.edu/ebeamweb/doc/patternprep/patternprep/proximity_main.html#:~:text=Alpha%2C%20generally%20representing%20the%20forward%2C%20or%20short-range%20scattering.,Gaussian%20to%20that%20in%20the%20forward%20Alpha%20Gaussian.).

**Comment by uvwatshu** [comment]
兄弟你也是做光刻工艺的呀，我们课题组没有机会让我接触到实际的机台，我自己一个人调研不是很清楚，想请教一下，它这个最后生成的pattern是不规则的，是不是只能用单电子束或者多电子束去生产呀，VSB应该是不适用的吧？VSB好像最好是规则的形状，不知道这方面你了解吗？

**Comment by maple367** [comment]
> 兄弟你也是做光刻工艺的呀，我们课题组没有机会让我接触到实际的机台，我自己一个人调研不是很清楚，想请教一下，它这个最后生成的pattern是不规则的，是不是只能用单电子束或者多电子束去生产呀，VSB应该是不适用的吧？VSB好像最好是规则的形状，不知道这方面你了解吗？

vsb没用过，只做过普通ebl，不知道你的特征线宽是多少，可能矢量扫描类型的ebl也满足你的需求。

**Comment by uvwatshu** [comment]
![854f1cef54e8482c4c6b61025153cbe](https://github.com/user-attachments/assets/731ef74b-588c-4477-ab1c-64ad49cb24a9)
![a0c8a9213e4ffa36bb85fbcaf05786f](https://github.com/user-attachments/assets/62c7f0cc-d537-4d68-bd77-2ed79a2aa0b0)
不好意思又来打扰您，最近在运行这个程序的时候发现同样的参数设置，图形输入的不同会有很大区别，这个可能是什么原因呀？我测试了一些数据集，发现当图片分布比较均匀的时候，它的效果就很好，但是当图片的分布相对没那么均匀的时候效果就不理想。

**Comment by maple367** [comment]
第一组图的physical field误差太大了，应该是迭代次数不够

**Comment by uvwatshu** [comment]
谢谢，问题已解决，调整了一下gtol增加迭代次数后得到了改善~
